-- local w_10 = math.floor(vim.o.columns * 0.1)
-- local h_10 = math.floor(vim.o.lines * 0.1)
-- local width = math.floor(vim.o.columns * 0.5)
-- local height = math.floor(vim.o.lines * 0.5)
-- local col = math.floor((vim.o.columns - width) / 2)
-- local row = math.floor((vim.o.lines - height) / 2)
--
-- local M = {}
-- local win = nil
-- ---@type vim.api.keyset.win_config
-- local windows = {
-- 	url = {
-- 		relative = "editor",
-- 		style = "minimal",
-- 		border = "double",
-- 		row = row,
-- 		col = col,
-- 		width = width,
-- 		height = height,
-- 	},
-- 	method = {
-- 		relative = "editor",
-- 		style = "minimal",
-- 		border = "double",
-- 		row = 0,
-- 		col = 0,
-- 		width = width,
-- 		height = 1,
-- 	},
-- }
--
-- local url_bar = nil
-- local url_buffer = {
-- 	buf = nil,
-- 	url = nil,
-- }
-- local method_bar = nil
-- local method_buffer = {
-- 	buf = nil,
-- 	method = nil,
-- }
--
-- local b = vim.api.nvim_create_buf(false, true)
-- local function open_window()
-- 	win = vim.api.nvim_open_win(b, true, {
-- 		relative = "editor",
-- 		style = "minimal",
-- 		border = "double",
-- 		row = row,
-- 		col = col,
-- 		width = width,
-- 		height = height,
-- 	})
-- end
--
-- local function set_layout()
-- 	local function handle_url()
-- 		url_buffer.buf = vim.api.nvim_create_buf(false, true)
-- 		url_bar = vim.api.nvim_open_win(url_buffer.buf, true, {
-- 			relative = "win",
-- 			border = "single",
-- 			win = win,
-- 			style = "minimal",
-- 			row = 0,
-- 			col = 0,
-- 			width = width - (w_10 * 2),
-- 			height = 1,
-- 		})
-- 		vim.api.nvim_buf_set_lines(url_buffer.buf, 0, -1, false, { "http://" })
-- 	end
-- 	local function handle_method() end
-- 	handle_url()
-- end
--
-- local function get_url()
-- 	if url_buffer then
-- 		url_buffer.url = vim.api.nvim_buf_get_lines(url_buffer.buf, 0, 1, false)[1]
-- 		print(url_buffer.url)
-- 	end
-- end
-- -- Toggle
-- M.toggle = function()
-- 	if win and vim.api.nvim_win_is_valid(win) then
-- 		vim.api.nvim_win_hide(win)
-- 		if url_bar and vim.api.nvim_win_is_valid(url_bar) then
-- 			vim.api.nvim_win_hide(url_bar)
-- 		end
-- 		return
-- 	end
-- 	vim.keymap.set({ "i", "n", "v" }, "<CR>", get_url, {})
-- 	open_window()
-- 	set_layout()
-- end
--
-- vim.keymap.set({ "i", "n", "v" }, "<leader><CR>", function()
-- 	M.toggle()
-- end)
-- return M
